apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
    role: {{ .Values.application.role }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
      role: {{ .Values.application.role }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
        role: {{ .Values.application.role }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: "{{ if .Values.image.registry }}{{ .Values.image.registry }}/{{ end }}{{ .Values.image.name }}"
          ports:
            - containerPort: {{ .Values.application.port }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.application.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelay }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.application.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelay }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            requests:
              memory: {{ .Values.resources.memory.request }}
              cpu: {{ .Values.resources.cpu.request }}
            limits:
              memory: {{ .Values.resources.memory.limit }}
              cpu: {{ .Values.resources.cpu.limit }}
