name: Firs Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      


# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps: 
#       - name: Print Hello World
#         run: |
#           echo "Hello World!"
#           echo "Goodbye"
